spring.application.name=backend
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5433/vault_db
spring.datasource.username=postgres
spring.datasource.password=root

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=4qhq8L6sN6fT7xZ9rE3uP2wA5dJ8kM4vC1gH5jK8lO2nB5xZ9rE3uP2wA5dJ8kM4
jwt.expiration=86400000